//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authentication.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ Email đã tồn tại.
        /// </summary>
        public static string EMAIL_AVAILABLE {
            get {
                return ResourceManager.GetString("EMAIL_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật {0}.
        /// </summary>
        public static string MSG_CAN_NOT_UPDATE {
            get {
                return ResourceManager.GetString("MSG_CAN_NOT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng chưa được gán quyền sử dụng thiết bị.
        /// </summary>
        public static string MSG_CAN_NOT_USE_DEVICE {
            get {
                return ResourceManager.GetString("MSG_CAN_NOT_USE_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu thành công.
        /// </summary>
        public static string MSG_CHANGE_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_CHANGE_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới {0} thành công..
        /// </summary>
        public static string MSG_CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa {0} thành công..
        /// </summary>
        public static string MSG_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn {0}..
        /// </summary>
        public static string MSG_DropDownList_CHOOSE {
            get {
                return ResourceManager.GetString("MSG_DropDownList_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chỉ hỗ trợ định dạng {1}..
        /// </summary>
        public static string MSG_FILE_UPLOAD {
            get {
                return ResourceManager.GetString("MSG_FILE_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng ảnh phải là {}.
        /// </summary>
        public static string MSG_FORMAT_IMAGE {
            get {
                return ResourceManager.GetString("MSG_FORMAT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thể để trống.
        /// </summary>
        public static string MSG_INPUT_NOT_EMPTY {
            get {
                return ResourceManager.GetString("MSG_INPUT_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chỉ cho phép nhập số từ {1} đến {2}..
        /// </summary>
        public static string MSG_INPUT_NUMBER_FROM_TO {
            get {
                return ResourceManager.GetString("MSG_INPUT_NUMBER_FROM_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chỉ cho phép nhập số không vượt quá {1}..
        /// </summary>
        public static string MSG_INPUT_NUMBER_MAX {
            get {
                return ResourceManager.GetString("MSG_INPUT_NUMBER_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chỉ cho phép nhập số lớn hơn {1}..
        /// </summary>
        public static string MSG_INPUT_NUMBER_MIN {
            get {
                return ResourceManager.GetString("MSG_INPUT_NUMBER_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chỉ cho phép nhập số..
        /// </summary>
        public static string MSG_INPUT_NUMBER_ONLY {
            get {
                return ResourceManager.GetString("MSG_INPUT_NUMBER_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng..
        /// </summary>
        public static string MSG_INVALID_ACCOUNT {
            get {
                return ResourceManager.GetString("MSG_INVALID_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string MSG_INVALID_DATA {
            get {
                return ResourceManager.GetString("MSG_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại.
        /// </summary>
        public static string MSG_IS_EXIST {
            get {
                return ResourceManager.GetString("MSG_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại.
        /// </summary>
        public static string MSG_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không trùng khớp.
        /// </summary>
        public static string MSG_PASS_CONFIRMPASS_DO_NOT_MATCH {
            get {
                return ResourceManager.GetString("MSG_PASS_CONFIRMPASS_DO_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài mật khẩu không được vượt quá 16 ký tự.
        /// </summary>
        public static string MSG_PASSWORD_MAX_LENGTH {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài mật khẩu phải có ít nhất 6 ký tự.
        /// </summary>
        public static string MSG_PASSWORD_MIN_LENGTH {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác.
        /// </summary>
        public static string MSG_PASSWORD_MISMATCH {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký quyền cho người dùng thành công.
        /// </summary>
        public static string MSG_REGISTER_ROLE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_REGISTER_ROLE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống.
        /// </summary>
        public static string MSG_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("MSG_REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải chứa ít nhất một {0}.
        /// </summary>
        public static string MSG_REQUIRED_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_REQUIRED_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra SSO thành công.
        /// </summary>
        public static string MSG_SSO_CHECK_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SSO_CHECK_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống.
        /// </summary>
        public static string MSG_SYSTEM_ERROR {
            get {
                return ResourceManager.GetString("MSG_SYSTEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhập {0} thành công..
        /// </summary>
        public static string MSG_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không hợp lệ.
        /// </summary>
        public static string MSG_VALIDATE_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh không đúng định dạng.
        /// </summary>
        public static string MSG_VALIDATE_EXTENSION_IMAGE {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_EXTENSION_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích cỡ của File không được vượt quá {} MB.
        /// </summary>
        public static string MSG_VALIDATE_MAX_LENGTH_FORM_FILE {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_MAX_LENGTH_FORM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset mật khẩu thành công.
        /// </summary>
        public static string RESET_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã tồn tại.
        /// </summary>
        public static string USERNAME_AVAILABLE {
            get {
                return ResourceManager.GetString("USERNAME_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được chứa ký tự đặc biệt.
        /// </summary>
        public static string USERNAME_NOT_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("USERNAME_NOT_SPECIAL_CHAR", resourceCulture);
            }
        }
    }
}
