//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVN.Core.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVN.Core.Resources.Messages.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.
        /// </summary>
        public static string MSG_AN_UNEXPECTED {
            get {
                return ResourceManager.GetString("MSG_AN_UNEXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string MSG_BAD_REQUEST {
            get {
                return ResourceManager.GetString("MSG_BAD_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is accessing your operation.
        /// </summary>
        public static string MSG_BLOCK_REQUEST {
            get {
                return ResourceManager.GetString("MSG_BLOCK_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture invalid.
        /// </summary>
        public static string MSG_CULTURE_ERROR {
            get {
                return ResourceManager.GetString("MSG_CULTURE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Bidden.
        /// </summary>
        public static string MSG_FOR_BIDDEN {
            get {
                return ResourceManager.GetString("MSG_FOR_BIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request time out.
        /// </summary>
        public static string MSG_REQUEST_TIME_OUT {
            get {
                return ResourceManager.GetString("MSG_REQUEST_TIME_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string MSG_RESOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_RESOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string MSG_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang bảo trì. Vui lòng liên hệ với Admin.
        /// </summary>
        public static string MSG_SYSTEM_ERROR {
            get {
                return ResourceManager.GetString("MSG_SYSTEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không hợp lệ.
        /// </summary>
        public static string MSG_TOKEN_INVALID {
            get {
                return ResourceManager.GetString("MSG_TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập chức năng này.
        /// </summary>
        public static string MSG_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("MSG_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessable entity.
        /// </summary>
        public static string MSG_UNPROCESSABLE_ENTITY {
            get {
                return ResourceManager.GetString("MSG_UNPROCESSABLE_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        public static string MSG_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("MSG_VALIDATION_FAILED", resourceCulture);
            }
        }
    }
}
